### ISSUE TITLE
How to get image temperature?

### ISSUE THREAD

**Issue by finnickniu** [elerac/EasyPySpin#2]
Hi, thanks for your great job. 

I am wondering how to get image or pixels temperature value.

**Comment by elerac** [comment]
Hi @finnickniu,

I think you are talking about the thermal camera... However, it seems that Spinnaker SDK only supports machine vision cameras (e.g., BlackFly, Flea3, etc.), not thermal cameras.

(In EasyPySpin, `cv2.CAP_PROP_TEMPERATURE` acquires the internal temperature of the camera.)

**Comment by finnickniu** [comment]
Hi elerac,

Thanks for your qucik reply. You are right, I am using flir Axx3 series thermal camera, and I am fresh in this area. I want to find a python/c++ sdk to get the temperature, do you have any idea?

Many Thanks.

**Comment by elerac** [comment]
[Here](https://flir.custhelp.com/app/answers/detail/a_id/3000) is a list of SDKs to control the flir cameras.
I don't have a thermal camera, so I don't know the details, but according to this list, File SDK or Atlas SDK is the right choice for thermal analysis.

**Comment by finnickniu** [comment]
Thanks!
