### ISSUE TITLE
Can't set gamma value

### ISSUE THREAD

**Issue by tristanle22** [elerac/EasyPySpin#5]
Hello,
I'm using the function videocapture.set(cv2.CAP_PROP_GAMMA, value) to set a gamma value, however, I got the following results
`_PySpin.SpinnakerException: Spinnaker: GenICam::AccessException= Node is not writable. : AccessException thrown in node 'Gamma' while calling 'Gamma.SetValue()' (file 'FloatT.h', line 83) [-2006]`

Do you know if there's any workaround?
Thanks!

**Comment by elerac** [comment]
Hi @tristanle22 !

As the error message says, the gamma value is not writable.
I had the same error, and it was because I had set `Gamma Enable` to `False`. So, check that `Gamma Enable` is set to `True` using SpinView (AnalogControl->GammaEnable).

**Comment by tristanle22** [comment]
Yup that seems to be the issue, thanks @elerac !
