### ISSUE TITLE
select video source by camera serial number

### ISSUE THREAD

**Issue by takmiyamott** [elerac/EasyPySpin#6]
Hi, thanks for the great tool!

Is it able to select the camera by its serial number?
something like follows:
    cam = EasyPySpin.VideoCapture(serial-number-here)

Thanks

**Comment by elerac** [comment]
Hi @takmiyamott !

Yes! You can use the serial number to select the camera.
Set serial number as `str` type, like below.
```python
cam = EasyPySpin.VideoCapture("19412150")
```

**Comment by takmiyamott** [comment]
Thank you for the reply!
I got it!
