### ISSUE TITLE
VideoCapture.get(cv2.CAP_PROR_FPS) return None

### ISSUE THREAD

**Issue by Umblife** [elerac/EasyPySpin#8]
Hello, thanks for your great job.

When I used the get() method of the VideoCapture class with a FLIR camera, I got unexpected value.

```python
>> vc = EasyPySpin.VideoCapture(0)
>> vc.set(cv2.CAP_PROP_FPS, 20)
True

# 20 is expected. But actually None is back
>> vc.get(cv2.CAP_PROR_FPS)
None
```

I found this,
https://github.com/elerac/EasyPySpin/blob/ea1aa5b116efb3569ca945bb7590169864262d0f/EasyPySpin/videocapture.py#L377-L380
so debugged "AcquisitionFrameRate" and "ExposureTime", but the exposure time is less than the frame time. 
```python
# debug
>> self.get_pyspin_value("AcquisitionFrameRate")
19.999350421098324  # 20fps -> frame time: 0.05sec
>> self.get_pyspin_value("ExposureTime")
15002.0 # micro sec -> 0.015 sec
```

I checked self.cam of VideoCapture class, but self.cam doesn't have an attribute "ResultingFrameRate". In fact, this get_pyspin_value() method called here also returns None by the following processing.
https://github.com/elerac/EasyPySpin/blob/ea1aa5b116efb3569ca945bb7590169864262d0f/EasyPySpin/videocapture.py#L632-L635

However, self.cam has "AcquisitionResultingFrameRate". Is this considered the same as the "ResultingFrameRate" in the original code ?
```python
# debug
>> self.get_pyspin_value("AcquisitionFrameRate")
19.999350421098324
>> self.get_pyspin_value("AcquisitionResultingFrameRate")
19.999350401098972  # Approximately the same value as "AcquisitionFrameRate" is returned
```

Thanks for your helping

**Comment by elerac** [comment]
Hi @Umblife !

Thanks for your great report!

As you say, `"ResultingFrameRate"` returns `None`, and `"AcquisitionResultingFrameRate"` is correct. 

I have completed the fix. Please check it.
